name: "Generate Installable Plugin Zip for Release"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release zip
        run: |
          # The desired folder name inside the zip file (your plugin's slug)
          PLUGIN_SLUG="php-sdk" 
          ZIP_FILE_NAME="$PLUGIN_SLUG.zip"

          # Use git archive with --prefix to specify the root folder name inside the zip
          git archive -o $ZIP_FILE_NAME --prefix $PLUGIN_SLUG/ HEAD

      - name: Upload plugin zip as release asset
        uses: softprops/action-gh-release@v1
        if: github.event.action == 'published'
        with:
          files: |
            php-sdk.zip
